# three node (two workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: KubeletConfiguration
    cgroupDriver: systemd
- role: worker
- role: worker
# ---
# three node (two workers) cluster config
# kind: Cluster
# apiVersion: kind.x-k8s.io/v1alpha4
# featureGates:
#   "ValidatingAdmissionPolicy": true
# nodes:
# - role: control-plane
# - role: worker
# - role: worker
---
# Six node (Three workers and Three Control Planes) cluster config
# kind: Cluster
# apiVersion: kind.x-k8s.io/v1alpha4
# nodes:
# - role: control-plane
#   image: kindest/node:v1.26.4@sha256:f4c0d87be03d6bea69f5e5dc0adb678bb498a190ee5c38422bf751541cebe92e
# - role: control-plane
# - role: control-plane
# - role: worker
# - role: worker
# - role: worker
