apiVersion: v1
kind: Service
metadata:
  name: helloapp
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: helloapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080